name: Mi Flujo de Trabajo

on:
  push:
    branches:
      - main

jobs:
  mi_trabajo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Ejecutar mi aplicación con contraseña oculta
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        chmod +x script.sh
        ./script.sh